{
  "openapi": "3.0.0",
  "info": {
    "title": "iFindy",
    "contact": {
      "name": "Guilherme Vieira de Paiva",
      "email": "guivpw68@gmail.com"
    },
    "version": "0.2",
    "x-codegen-settings": {
      "Nullify404": false,
      "GenerateAsyncCode": true,
      "UseMethodPrefix": false,
      "UseModelPostfix": false,
      "UseControllerPrefix": true,
      "UseEnumPostfix": true,
      "CollectParameters": false,
      "UseConstructorsForConfig": false,
      "UseCommonSDKLibrary": false,
      "iOSUseAppInfoPlist": false,
      "AndroidUseAppManifest": false,
      "BodySerialization": 0,
      "EnableAdditionalModelProperties": false,
      "PreserveParameterOrder": true,
      "AppendContentHeaders": true,
      "iOSGenerateCoreData": false,
      "GenerateInterfaces": false,
      "NodeHttpClient": "NODE_REQUEST",
      "ValidateRequiredParameters": false,
      "JavaUsePropertiesConfig": false,
      "Timeout": 0.0,
      "StoreTimezoneInformation": false,
      "EnablePHPComposerVersionString": false,
      "EnableLogging": false,
      "ArraySerialization": "Indexed",
      "ModelSerializationScheme": "Json",
      "UseExceptionPrefix": true,
      "RunscopeEnabled": false,
      "AndroidHttpClient": "ANDROID_OK",
      "ObjCHttpClient": "UNIREST",
      "CSharpHttpClient": "UNIREST",
      "PHPHttpClient": "UNIREST",
      "JavaHttpClient": "JAVA_OK",
      "ParameterArrayFormat": "ParamArrayWithIndex",
      "SecurityProtocols": ["Ssl3", "Tls"],
      "GenerateTravisConfig": false,
      "GenerateCircleConfig": false,
      "GenerateAppveyorConfig": false,
      "GenerateJenkinsConfig": false,
      "EnableHttpCache": false,
      "Retries": 0,
      "RetryInterval": 1.0,
      "GenerateAdvancedDocs": true,
      "UnderscoreNumbers": true,
      "UseSingletonPattern": true,
      "DisableLinting": false,
      "ApplyCustomizations": [],
      "SortResources": false,
      "AllowSkippingSSLCertVerification": false,
      "DoNotSplitWords": [],
      "EnableGlobalUserAgent": true,
      "ReturnCompleteHttpResponse": false,
      "GenerateModels": true,
      "GenerateExceptions": true,
      "IgnoreIfNullJson": false,
      "DisableDocs": false,
      "LiftParameterDescriptionFromCustomType": false,
      "ThrowForHttpErrorStatusCodes": true,
      "ResponseMapping": {
        "Type": "Simple"
      },
      "ForceKeywordArgsInRuby": false,
      "SymbolizeHashKeysInRuby": false,
      "UsageExampleEndpoint": {
        "Description": "",
        "EndpointGroupName": "",
        "EndpointName": ""
      },
      "IsLatestVersion": false,
      "EnableImmutableModels": false,
      "GenerateEnums": true,
      "BackoffFactor": 2.0,
      "StatusCodesToRetry": [408, 413, 429, 500, 502, 503, 504, 521, 522, 524],
      "RequestMethodsToRetry": ["GET", "PUT"],
      "UserConfigurableRetries": true,
      "UseEndpointMethodName": false,
      "EncodeTemplateParameters": true,
      "GenerateExamplesForOptionalFields": false,
      "MultitargetDotnetVersions": false,
      "BackoffMax": 0.0,
      "RetryOnTimeout": true,
      "EnableCookies": false,
      "EnableJsonPassThroughForAny": false
    },
    "x-server-configuration": {
      "default-environment": "Production",
      "default-server": "Server Https",
      "environments": [
        {
          "name": "Production",
          "description": "Ambiente de produção hospedado pelo Heroku",
          "servers": [
            {
              "name": "Server Https",
              "url": "https://eventos-v1-api.herokuapp.com"
            },
            {
              "name": "Server Websocket",
              "url": "ws://eventos-v1-api.herokuapp.com"
            }
          ]
        },
        {
          "name": "Desenvolvimento",
          "description": "Ambiente de desenvolvimento hospedado na porta local 3000",
          "servers": [
            {
              "name": "Server Https",
              "url": "http://localhost:3000"
            },
            {
              "name": "Server Websocket",
              "url": "ws://localhost:3000"
            }
          ]
        }
      ],
      "parameters": []
    },
    "x-image-uri": "https://www.calendariodovestibular.com.br/wp-content/uploads/2020/08/vestibular-fiap-2022.jpg"
  },
  "servers": [
    {
      "url": "https://eventos-v1-api.herokuapp.com",
      "description": "Ambiente de produção hospedado pelo Heroku",
      "variables": {}
    },
    {
      "url": "ws://eventos-v1-api.herokuapp.com",
      "description": "Ambiente de produção hospedado pelo Heroku",
      "variables": {}
    },
    {
      "url": "http://localhost:3000",
      "description": "Ambiente de desenvolvimento hospedado na porta local 3000",
      "variables": {}
    },
    {
      "url": "ws://localhost:3000",
      "description": "Ambiente de desenvolvimento hospedado na porta local 3000",
      "variables": {}
    }
  ],
  "paths": {
    "/users/login": {
      "post": {
        "tags": ["Users"],
        "summary": "Login",
        "description": "Autentica um usuário utilizando com a senha e e-mail fornecidos",
        "operationId": "Login",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              },
              "example": {
                "email": "guivpw68@gmail.com",
                "password": "Guigui123"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuthResponse"
                },
                "example": {
                  "user": {
                    "id": 1,
                    "name": "Guilherme",
                    "avatarUrl": null,
                    "email": "guivpw68@gmail.com",
                    "birth": "2002-02-08T00:00:00.000Z",
                    "phone": "11988900772",
                    "createdAt": "2022-04-19T23:36:52.000Z",
                    "updatedAt": "2022-04-19T23:36:52.000Z"
                  },
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ikd1aWxoZXJtZSIsImVtYWlsIjoiZ3VpdnB3NjhAZ21haWwuY29tIiwiYXZhdGFyVXJsIjpudWxsLCJpYXQiOjE2NTA5MTg0NTcsImV4cCI6MTY1MTUyMzI1NywiaXNzIjoibWV0YWZ5In0.wFa0y9AKX6hVG2_a60Vf18L4Oy6JXgp4v29wJ4Z5mI1"
                }
              }
            }
          }
        },
        "deprecated": false,
        "security": [],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        },
        "x-unitTests": []
      }
    },
    "/users/signup": {
      "post": {
        "tags": ["Users"],
        "summary": "Signup",
        "description": "Realiza a criação de um usuário.",
        "operationId": "Signup",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SignupRequest"
              },
              "example": {
                "name": "Guilherme",
                "email": "guivpw68@gmail.com",
                "password": "Guigui123",
                "confirmPassword": "Guigui123",
                "phone": "11988900999",
                "birth": "2002-02-08"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuthResponse"
                },
                "example": {
                  "user": {
                    "id": 1,
                    "name": "Guilherme",
                    "email": "guivpw68@gmail.com",
                    "birth": "2002-02-08T00:00:00.000Z",
                    "phone": "11988900772",
                    "createdAt": "2022-04-20T20:48:55.000Z",
                    "updatedAt": "2022-04-20T20:48:55.000Z"
                  },
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6Ikd1aWxoZXJtZSIsImVtYWlsIjoiZ3VpemluQGdtYWlsLmNvbSIsImF2YXRhclVybCI6bnVsbCwiaWF0IjoxNjUwOTE5NzM1LCJleHAiOjE2NTE1MjQ1MzUsImlzcyI6Im1ldGFmeSJ9.3In8Aag3NHUJmPSOWup1q9T91uc5S2ymniDklLDaAVA"
                }
              }
            }
          }
        },
        "deprecated": false,
        "security": [],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        },
        "x-unitTests": []
      }
    },
    "/users/{userId}/creator": {
      "post": {
        "tags": ["Users"],
        "summary": "Criar Criador de Eventos",
        "description": "Realiza a associação de um usuário a um criador de eventos caso esse já não exista.",
        "operationId": "CriarCriadordeEventos",
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "description": "Id do usuário",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "integer",
              "format": "int32",
              "example": 1
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Creator"
                }
              }
            }
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        },
        "x-unitTests": []
      }
    },
    "/creator/{idCreator}/event": {
      "post": {
        "tags": ["Events"],
        "summary": "Create Event",
        "description": "Realiza a criação de um evento como um criador de eventos.",
        "operationId": "CreateEvent",
        "parameters": [
          {
            "name": "idCreator",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "integer",
              "format": "int32",
              "example": 1
            }
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateEventRequest"
              },
              "example": {
                "name": "Eventop",
                "description": "Muito legal",
                "startAt": "2022-04-22T07:00:00.000Z",
                "endsAt": "2022-04-22T08:00:00.000Z",
                "latitude": -23.4058165,
                "longitude": -46.3446359,
                "address": "Avenida São Lucas, 395, Nova Arujá, Arujá"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Event"
                }
              }
            }
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        },
        "x-unitTests": []
      }
    },
    "/events": {
      "get": {
        "tags": ["Events"],
        "summary": "Find many Events",
        "description": "Realiza a busca de vários eventos a partir do nome, id do criador ou avaliação mínima. \nTambém é possível realizar a busca de vários eventos num raio de tantos quilômetros.",
        "operationId": "FindmanyEvents",
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "description": "Número da página atual",
            "style": "form",
            "explode": true,
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 1,
              "example": 1
            }
          },
          {
            "name": "limit",
            "in": "query",
            "description": "Número de eventos a retornar",
            "style": "form",
            "explode": true,
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 50,
              "example": 1
            }
          },
          {
            "name": "name",
            "in": "query",
            "description": "Nome do evento ou de alguma parte sua",
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string",
              "example": "top"
            }
          },
          {
            "name": "idCreator",
            "in": "query",
            "description": "Número do criador do evento",
            "style": "form",
            "explode": true,
            "schema": {
              "type": "integer",
              "format": "int32",
              "example": 1
            }
          },
          {
            "name": "latitude",
            "in": "query",
            "description": "Latitude a ser procurada, deve ser utilizado junto da longitude.",
            "style": "form",
            "explode": true,
            "schema": {
              "type": "number",
              "format": "double",
              "example": -23.4058165
            }
          },
          {
            "name": "longitude",
            "in": "query",
            "description": "Longitude a ser procurada, deve ser utilizado junto da longitude.",
            "style": "form",
            "explode": true,
            "schema": {
              "type": "number",
              "format": "double",
              "example": -46.3446359
            }
          },
          {
            "name": "kilometers",
            "in": "query",
            "description": "Define o raio em quilômetros que os eventos serão buscados.",
            "style": "form",
            "explode": true,
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 10,
              "example": 10
            }
          },
          {
            "name": "rating",
            "in": "query",
            "description": "Avaliação mínima do evento",
            "style": "form",
            "explode": true,
            "schema": {
              "type": "integer",
              "format": "int32",
              "example": 2
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Event"
                  },
                  "example": [
                    {
                      "id": 1,
                      "name": "Eventop",
                      "description": "Muito legal",
                      "address": "Avenida São Lucas, 395, Nova Arujá, Arujá",
                      "idCreator": 1,
                      "latitude": "-23.4058165",
                      "longitude": "-46.3446359",
                      "rating": null,
                      "endsAt": "2022-04-22T08:00:00.000Z",
                      "startAt": "2022-04-22T07:00:00.000Z",
                      "createdAt": "2022-04-20T00:00:00.000Z",
                      "updatedAt": "2022-04-20T00:00:00.000Z",
                      "creator": {
                        "rating": null,
                        "user": {
                          "id": 1,
                          "name": "Guilherme",
                          "avatarUrl": null
                        }
                      }
                    }
                  ]
                },
                "example": [
                  {
                    "id": 1,
                    "name": "Eventop",
                    "description": "Muito legal",
                    "address": "Avenida São Lucas, 395, Nova Arujá, Arujá",
                    "idCreator": 1,
                    "latitude": "-23.4058165",
                    "longitude": "-46.3446359",
                    "rating": null,
                    "endsAt": "2022-04-22T08:00:00.000Z",
                    "startAt": "2022-04-22T07:00:00.000Z",
                    "createdAt": "2022-04-20T00:00:00.000Z",
                    "updatedAt": "2022-04-20T00:00:00.000Z",
                    "creator": {
                      "rating": null,
                      "user": {
                        "id": 1,
                        "name": "Guilherme",
                        "avatarUrl": null
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        "deprecated": false,
        "security": [],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        },
        "x-unitTests": []
      }
    },
    "/": {
      "get": {
        "tags": ["Websocket"],
        "summary": "Eventos próximos em tempo real",
        "description": "Retorna eventos baseados na localização do usuário num raio de 10 quilômetro por padrão.\n\nObs: Essa chamada deve ser feita via websocket não https. Caso você tente executar essa chamada, ela irá falhar.\nÉ recomendado utilizar alguma ferramenta externa para testar essa rota, como o Postman por exemplo.",
        "operationId": "Eventospróximosemtemporeal",
        "parameters": [
          {
            "name": "server:event:search-near",
            "in": "query",
            "description": "Evento a ser escutado antes de realizar o envio da mensagem.",
            "required": true,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "object"
            }
          },
          {
            "name": "client:event:search-near",
            "in": "query",
            "description": "Evento a ser emitido para o servidor.",
            "required": true,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "object",
              "example": {
                "latitude": -23.4058165,
                "longitude": -46.3446359
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Event"
                }
              }
            }
          }
        },
        "deprecated": false,
        "servers": [
          {
            "url": "ws://eventos-v1-api.herokuapp.com",
            "variables": {}
          },
          {
            "url": "ws://localhost:3000",
            "variables": {}
          }
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": true
        },
        "x-unitTests": [],
        "x-server-name": "Server Websocket"
      }
    }
  },
  "components": {
    "schemas": {
      "LoginRequest": {
        "title": "LoginRequest",
        "required": ["email", "password"],
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "example": {
          "email": "guivpw68@gmail.com",
          "password": "Guigui123"
        }
      },
      "SignupRequest": {
        "title": "SignupRequest",
        "required": ["name", "email", "password", "confirmPassword", "phone", "birth"],
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "Guilherme"
          },
          "email": {
            "type": "string",
            "example": "email@example.com"
          },
          "password": {
            "type": "string",
            "example": "guigui123"
          },
          "confirmPassword": {
            "type": "string",
            "example": "guigui123"
          },
          "phone": {
            "type": "string",
            "example": "1198899999"
          },
          "birth": {
            "type": "string"
          },
          "avatarUrl": {
            "type": "string",
            "description": "Url da imagem do usuário",
            "example": "https://i.imgur.com/UfRtjxV.jpg"
          }
        },
        "example": {
          "name": "Guilherme",
          "email": "guivpw68@gmail.com",
          "password": "Guigui123",
          "confirmPassword": "Top",
          "phone": "11988900772",
          "birth": "2002-02-08"
        }
      },
      "CreateEventRequest": {
        "title": "CreateEventRequest",
        "required": ["name", "description", "startAt", "endsAt", "latitude", "longitude", "address"],
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Nome do evento",
            "example": "Eventop"
          },
          "description": {
            "type": "string",
            "description": "Descrição do evento",
            "example": "Muito legal"
          },
          "startAt": {
            "type": "string",
            "description": "Data e hora que o evento se iniciará. O campo aceita apenas o formato ISO",
            "example": "\"2022-04-22T07:00:00.000Z\""
          },
          "endsAt": {
            "type": "string",
            "description": "Data e hora que o evento se encerrará. O campo aceita apenas o formato ISO",
            "example": "\"2022-04-22T08:00:00.000Z\""
          },
          "latitude": {
            "type": "number",
            "description": "Latitude do evento",
            "example": -23.4058165
          },
          "longitude": {
            "type": "number",
            "description": "Longitude do evento",
            "example": -46.3446359
          },
          "address": {
            "type": "string",
            "description": "Endereço do evento",
            "example": "Avenida São Lucas, 395, Nova Arujá, Arujá"
          }
        },
        "description": "Descreve o corpo da requisição de criação de um evento.",
        "example": {
          "name": "Eventop",
          "description": "Muito legal",
          "startAt": "2022-04-22T07:00:00.000Z",
          "endsAt": "2022-04-22T08:00:00.000Z",
          "latitude": -23.4058165,
          "longitude": -46.3446359,
          "address": "Avenida São Lucas, 395, Nova Arujá, Arujá"
        }
      },
      "AuthResponse": {
        "title": "AuthResponse",
        "required": ["user", "token"],
        "type": "object",
        "properties": {
          "user": {
            "$ref": "#/components/schemas/User"
          },
          "token": {
            "type": "string",
            "description": "Token de acesso que deverá ser enviado no Header Authorization",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ikd1aWxoZXJtZSIsImVtYWlsIjoiZ3VpdnB3NjhAZ21haWwuY29tIiwiYXZhdGFyVXJsIjpudWxsLCJpYXQiOjE2NTA5MTY5MDEsImV4cCI6MTY1MTUyMTcwMSwiaXNzIjoibWV0YWZ5In0.qrw7dckkCrf71pe1jDoFPQTNNZZQWBQx29u1oKDB4uh"
          }
        },
        "description": "Resposta padrão de chamadas de autenticação",
        "example": {
          "user": {
            "id": 1,
            "name": "Guilherme",
            "email": "guivpw68@gmail.com",
            "birth": "2002-02-08T00:00:00.000Z",
            "phone": "11988999772",
            "createdAt": "2022-04-10T20:00:00.000Z",
            "updatedAt": "2022-04-10T20:00:00.000Z"
          },
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ikd1aWxoZXJtZSIsImVtYWlsIjoiZ3VpdnB3NjhAZ21haWwuY29tIiwiYXZhdGFyVXJsIjpudWxsLCJpYXQiOjE2NTA5MTY5MDEsImV4cCI6MTY1MTUyMTcwMSwiaXNzIjoibWV0YWZ5In0.qrw7dckkCrf71pe1jDoFPQTNNZZQWBQx29u1oKDB4uh"
        }
      },
      "User": {
        "title": "User",
        "required": ["id", "name", "email", "birth", "phone", "createdAt", "updatedAt"],
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32",
            "example": 1
          },
          "name": {
            "type": "string",
            "example": "Guilherme"
          },
          "email": {
            "type": "string",
            "example": "guivpw68@gmail.com"
          },
          "birth": {
            "type": "string",
            "example": "2002-02-08T00:00:00.000Z"
          },
          "phone": {
            "type": "string",
            "example": "11988900772"
          },
          "createdAt": {
            "type": "string",
            "example": "2022-04-25T20:01:42.000Z"
          },
          "updatedAt": {
            "type": "string",
            "example": "2022-04-25T20:01:42.000Z"
          }
        },
        "description": "Modelo do usuário",
        "example": {
          "id": 1,
          "name": "Guilherme",
          "email": "guivpw68@gmail.com",
          "birth": "2002-02-08T00:00:00.000Z",
          "phone": "11988999772",
          "createdAt": "2022-04-10T20:00:00.000Z",
          "updatedAt": "2022-04-10T20:00:00.000Z"
        }
      },
      "Event": {
        "title": "Event",
        "required": [
          "id",
          "name",
          "description",
          "address",
          "idCreator",
          "latitude",
          "longitude",
          "rating",
          "endsAt",
          "startAt",
          "createdAt",
          "updatedAt"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "Id do evento",
            "format": "int32",
            "example": 1
          },
          "name": {
            "type": "string",
            "description": "Nome do evento",
            "example": "Eventop"
          },
          "description": {
            "type": "string",
            "description": "Descrição do evento",
            "example": "Muito legal"
          },
          "address": {
            "type": "string",
            "description": "Endereço do evento",
            "example": "Avenida São Lucas, 395, Nova Arujá, Arujá"
          },
          "idCreator": {
            "type": "integer",
            "description": "Id do criador",
            "format": "int32",
            "example": 1
          },
          "latitude": {
            "type": "string",
            "description": "Latitude do evento",
            "example": "-23.4058165"
          },
          "longitude": {
            "type": "string",
            "description": "Longitude do evento",
            "example": "-46.3446359"
          },
          "rating": {
            "type": "number",
            "description": "Avaliação do evento",
            "nullable": true,
            "example": 4.2
          },
          "endsAt": {
            "type": "string",
            "description": "Data e hora que o evento se encerrará. O campo aceita apenas o formato ISO",
            "example": "2022-04-22T08:00:00.000Z"
          },
          "startAt": {
            "type": "string",
            "description": "Data e hora que o evento se iniciará. O campo aceita apenas o formato ISO",
            "example": "2022-04-22T07:00:00.000Z"
          },
          "createdAt": {
            "type": "string",
            "description": "Data e hora de criação do evento",
            "example": "2022-04-20T00:00:00.000Z"
          },
          "updatedAt": {
            "type": "string",
            "description": "Data e hora da ultima mudança no evento",
            "example": "2022-04-20T00:00:00.000Z"
          }
        },
        "description": "",
        "example": {
          "id": 1,
          "name": "Eventop",
          "description": "Muito legal",
          "address": "Avenida São Lucas, 395, Nova Arujá, Arujá",
          "idCreator": 1,
          "latitude": "-23.4058165",
          "longitude": "-46.3446359",
          "rating": null,
          "endsAt": "2022-04-22T08:00:00.000Z",
          "startAt": "2022-04-22T07:00:00.000Z",
          "createdAt": "2022-04-20T00:00:00.000Z",
          "updatedAt": "2022-04-20T00:00:00.000Z"
        }
      },
      "Creator": {
        "title": "Creator",
        "required": ["id", "idUser", "rating", "createdAt", "updatedAt"],
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "Id do criador",
            "format": "int32",
            "example": 1
          },
          "idUser": {
            "type": "integer",
            "description": "Id do usuário associado ao criador",
            "format": "int32",
            "example": 1
          },
          "rating": {
            "type": "number",
            "description": "Avaliação do criador",
            "nullable": true,
            "example": 4.5
          },
          "createdAt": {
            "type": "string",
            "description": "Data e hora de criação",
            "example": "2022-04-25T20:51:44.000Z"
          },
          "updatedAt": {
            "type": "string",
            "description": "Data e hora da última edição",
            "example": "2022-04-25T20:51:44.000Z"
          }
        },
        "description": "Modelo do criador de eventos",
        "example": {
          "id": 1,
          "idUser": 1,
          "rating": null,
          "createdAt": "2022-04-20T20:00:00.000Z",
          "updatedAt": "2022-04-20T20:00:00.000Z"
        }
      }
    },
    "securitySchemes": {
      "bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "security": [
    {
      "bearer": []
    }
  ],
  "tags": [
    {
      "name": "Users"
    },
    {
      "name": "Events"
    },
    {
      "name": "Websocket",
      "description": ""
    }
  ]
}
